### ISSUE TITLE
Multiple cheroot issues for Bottle < 0.13-dev and 0.12.x

### ISSUE THREAD

**Issue by mrdc** [nickbabcock/bottle-ssl#64]
Hello,

When using
```python
options = {
   'certfile': "certfile.pem",
   'keyfile': "keyfile.pem"
}
run(host='0.0.0.0', port=8900, server='cheroot', debug=False, options=options)
```
for Bottle version < 0.13 (for example, Bottle 0.12.19) - the following error occurs:
```
Traceback (most recent call last):
  File "bottle.py", line 3121, in run
    raise ValueError("Unknown or unsupported server: %r" % server)
ValueError: Unknown or unsupported server: <module 'cheroot' from '//site-packages//cheroot//__init__.py'>
```

when I change the `server='cheroot'` to `server='cherrypy'` I get this error:

```
Traceback (most recent call last):
  File "site-packages/bottle.py", line 3133, in run
    server.run(app)
  File "site-packages/bottle.py", line 2795, in run
    from cherrypy import wsgiserver
ImportError: cannot import name 'wsgiserver' from 'cherrypy' (site-packages/cherrypy/__init__.py)
```
Using this fix for the above mentioned import error  makes no difference - the same import error:

```python
try:
    from cheroot.wsgi import Server as WSGIServer
except ImportError:
    from cherrypy.wsgiserver import CherryPyWSGIServer as WSGIServer
```

To use cheroot with Bottle 0.13-dev some changes should be made:
Not working in 0.13-dev:
```python
 options = {
   'certfile': "certfile.pem",
   'keyfile': "keyfile.pem"
 }

run(host='0.0.0.0', port=8900, server='cheroot', debug=False, options=options)
```
should be changed to:
```python
certfile = "certfile.pem"
keyfile = "keyfile.pem"

run(host='0.0.0.0', port=8900, server='cheroot', debug=False,  certfile=certfile, keyfile=keyfile )
```
Otherwise this error occurs:
```
 server = wsgi.Server(**self.options)
TypeError: __init__() got an unexpected keyword argument 'options'
```

**Comment by nickbabcock** [comment]
Thank you for pointing this out. In order to avoid needing to juggle dependencies I've updated the readme to create a bottle adapter off of cheroot directly.
